[package]
name = "vkrs"
version = "0.1.0"
authors = ["Kai Wohlfahrt <kai.scorpio@gmail.com>"]

[dependencies]
libc = "0.2"
bitflags = "0.7"

[dev-dependencies]
compiletest_rs = "0.2"
clippy = "~0.0.76"
